# MultiLayer Perceptron - Basic

In [1]:
# Load library
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

## Deep Learning Model study

In [2]:
# def class for MLP
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.mlp1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.mlp2 = nn.Linear(hidden_size, num_classes)  
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        out = self.mlp1(x)
        out = self.relu(out)
        out = self.mlp2(out)
        out = self.softmax(out)
        return out

In [3]:
# check CUDA or CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [4]:
# def input paramters
input_size = 28*28 # MNIST image size
hidden_size = 50 # number of hidden neurals
num_classes = 10 # number of classes

model = NeuralNet( input_size, hidden_size, num_classes)
print(model)

NeuralNet(
  (mlp1): Linear(in_features=784, out_features=50, bias=True)
  (relu): ReLU()
  (mlp2): Linear(in_features=50, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)


In [5]:
# gen test data and prediction
data = torch.rand(1,28*28).to(device)
pred = model(data)
y_hat = pred.argmax(1)
print("full prediction is : ", pred)
print("prediction is : ", y_hat)

full prediction is :  tensor([[0.0966, 0.0825, 0.1117, 0.1205, 0.0899, 0.1054, 0.1000, 0.1006, 0.1078,
         0.0851]], grad_fn=<SoftmaxBackward0>)
prediction is :  tensor([3])


## torch.ReLU study

In [6]:
# gen test data
x = torch.randn(3,28,28)
# test ReLU
be_relu = x[0][0]
print("before relu is : ", be_relu )
relu = nn.ReLU()
af_relu = relu(be_relu)
print("after relu is : ", af_relu )

before relu is :  tensor([-1.2185, -0.8429,  0.4079,  0.2938,  0.0479,  0.8280, -1.1439, -0.9438,
         1.0315,  1.7447, -1.5439,  0.0391,  0.2794, -0.3086, -0.8768, -2.2528,
         0.0790,  1.2323, -1.4270,  0.3610, -0.0031,  1.0026, -0.6192,  0.7143,
        -0.3116, -0.9237, -0.6233, -0.6657])
after relu is :  tensor([0.0000, 0.0000, 0.4079, 0.2938, 0.0479, 0.8280, 0.0000, 0.0000, 1.0315,
        1.7447, 0.0000, 0.0391, 0.2794, 0.0000, 0.0000, 0.0000, 0.0790, 1.2323,
        0.0000, 0.3610, 0.0000, 1.0026, 0.0000, 0.7143, 0.0000, 0.0000, 0.0000,
        0.0000])


## torch.Softmax study

In [7]:
x = torch.randn(1,10)
x

tensor([[-0.9422,  0.9728, -1.4662,  0.3217, -0.1861,  1.9047, -1.6034, -0.2755,
          0.7304,  0.4030]])

In [8]:
softmax = nn.Softmax( dim=1 )
pred = softmax( x )
print("before : ", x )
print("after : ", pred )
print("pred.sum() is : ", pred.sum())

before :  tensor([[-0.9422,  0.9728, -1.4662,  0.3217, -0.1861,  1.9047, -1.6034, -0.2755,
          0.7304,  0.4030]])
after :  tensor([[0.0233, 0.1582, 0.0138, 0.0825, 0.0496, 0.4016, 0.0120, 0.0454, 0.1241,
         0.0895]])
pred.sum() is :  tensor(1.)


## torch.Sequential study

In [9]:
# default
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.mlp1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.mlp2 = nn.Linear(hidden_size, num_classes)  
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        out = self.mlp1(x)
        out = self.relu(out)
        out = self.mlp2(out)
        out = self.softmax(out)
        return out

In [10]:
# input paramters
input_size = 28*28*1 # MNIST image size
hidden_size = 100 # hyper parameter
num_classes = 10 # class number

# def model
model = NeuralNet(input_size, hidden_size, num_classes).to(device)
print(model)

NeuralNet(
  (mlp1): Linear(in_features=784, out_features=100, bias=True)
  (relu): ReLU()
  (mlp2): Linear(in_features=100, out_features=10, bias=True)
  (softmax): Softmax(dim=1)
)


In [11]:
# nn.Sequential : 

class NeuralNet2(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet2, self).__init__()
        sequential = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, num_classes),
            nn.Softmax(dim=1),
        )
    def forward(self, x):
        out = self.sequential(x)
        return out

In [12]:
# input paramters
input_size = 28*28*1 # MNIST image size
hidden_size = 100 # hyper parameter
num_classes = 10 # class number

# def model
model = NeuralNet2(input_size, hidden_size, num_classes).to(device)
print(model)

NeuralNet2()


# Loss Function
## Cross Entropy

In [13]:
x = torch.randn(3)
y = torch.tensor([0.0,1.0,0.0])
print(x)
print(y)

tensor([ 0.4460,  1.9138, -0.1390])
tensor([0., 1., 0.])


In [14]:
# binary cross entropy
bce_loss = nn.BCELoss()
sigmoid = nn.Sigmoid()

x_sig = sigmoid( x )
print( "BCE loss is : ", bce_loss( x_sig, y ) )

BCE loss is :  tensor(0.5682)


In [15]:
# binary cross entropy with logit loss - it has sigmoid inside
bce_logit_loss = nn.BCEWithLogitsLoss()
print( "BCE with logit loss is : ", bce_logit_loss( x, y ) )

BCE with logit loss is :  tensor(0.5682)


In [16]:
## Cross Entropy

In [17]:
x = torch.randn(1,10)
y = torch.tensor([1])
print(x)
print(y)

tensor([[ 2.2581, -0.7115,  0.1314, -0.4764,  0.3715, -0.8308, -1.0442, -0.1683,
          0.2220,  0.7409]])
tensor([1])


In [18]:
croosentropy = nn.CrossEntropyLoss()
print( "Cross Entropy Loss is : ", croosentropy(x, y) )

Cross Entropy Loss is :  tensor(3.6154)


## MSE

In [19]:
x = torch.randn(1,10)
y = torch.randn(1,10)
mse_loss = nn.MSELoss()
print( "MSE loss is : ", mse_loss( x, y ) )

MSE loss is :  tensor(2.0113)
